apiVersion: v1
kind: Service
metadata:
  name: tts-service
  namespace: dag-system
spec:
  type: ClusterIP
  selector:
    app: tts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000