apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-config
  namespace: dag-system
data:
  redis.conf: |
    cluster-enabled yes
    cluster-node-timeout 5000
    appendonly yes
    dir /data
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: dag-system
spec:
  serviceName: redis-cluster
  replicas: 4
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["redis-cluster"]
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: redis
          image: redis:alpine
          command: 
            - sh
            - -c
            - |
              mkdir -p /data/$(hostname)
              exec redis-server /etc/redis/redis.conf --dir /data/$(hostname)
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 6379
              name: client
            - containerPort: 16379
              name: gossip
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis/redis.conf
              subPath: redis.conf
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - redis-cli
                - -c
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                - -c
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: redis-config
          configMap:
            name: redis-cluster-config
            items:
              - key: redis.conf
                path: redis.conf
        - name: redis-data
          hostPath:
            path: /tmp/redis-data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: dag-system
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: client
    - port: 16379
      targetPort: 16379
      name: gossip
  selector:
    app: redis-cluster
  clusterIP: None