apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-controller
  namespace: dag-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dependency-controller
  template:
    metadata:
      labels:
        app: dependency-controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: controller
          image: docker.io/weimengze/cloud-computing-dependency:v5
          env:
            - name: REDIS_ADDRS
              value: "redis-cluster-0.redis-cluster.dag-system.svc.cluster.local:6379,redis-cluster-1.redis-cluster.dag-system.svc.cluster.local:6379,redis-cluster-2.redis-cluster.dag-system.svc.cluster.local:6379,redis-cluster-3.redis-cluster.dag-system.svc.cluster.local:6379,redis-cluster-4.redis-cluster.dag-system.svc.cluster.local:6379,redis-cluster-5.redis-cluster.dag-system.svc.cluster.local:6379"
            - name: CONCURRENT_HANDLERS
              value: "100"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"