apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt-deployment
  namespace: dag-system
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: stt
  template:
    metadata:
      labels:
        app: stt
    spec:
      containers:
        - name: stt
          image: docker.io/liuyi585851/labubuai-stt:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
          env:
            - name: AWS_REGION
              value: "us-east-1"
          envFrom:
            - secretRef:
              name: google-secret
            - secretRef:
              name: aws-secret    