apiVersion: v1
kind: Service
metadata:
  name: stt-service
  namespace: dag-system
spec:
  type: ClusterIP
  selector:
    app: stt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000