apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
  namespace: dag-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: springboot-login
          image: docker.io/weimengze/cloud-computing-login:v6
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: login-config
            - secretRef:
                name: login-secret