apiVersion: v1
kind: ConfigMap
metadata:
  name: login-config
  namespace: dag-system
data:
  SPRING_DATA_REDIS_CLUSTER_NODES: |
    redis-cluster-0.redis-cluster.dag-system.svc.cluster.local:6379,
    redis-cluster-1.redis-cluster.dag-system.svc.cluster.local:6379,
    redis-cluster-2.redis-cluster.dag-system.svc.cluster.local:6379,
    redis-cluster-3.redis-cluster.dag-system.svc.cluster.local:6379,
    redis-cluster-4.redis-cluster.dag-system.svc.cluster.local:6379,
    redis-cluster-5.redis-cluster.dag-system.svc.cluster.local:6379
  SPRING_DATA_REDIS_CLUSTER_MAX_REDIRECTS: "3"
  SPRING_DATA_REDIS_TIMEOUT: "5000ms"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "465"
  SPRING_MAIL_PROTOCOL: "smtps"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE: "true"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_DATASOURCE_NAME: "cloud"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.dag-system.svc.cluster.local:5432/cloud?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai"
  MYBATIS_PLUS_MAPPER_LOCATIONS: "classpath*:/mapper/**Mapper.xml"
  MYBATIS_PLUS_CONFIGURATION_LOG_IMPL: "org.apache.ibatis.logging.stdout.StdOutImpl"
  SPRING_APPLICATION_NAME: "cloud-computing-login"
  SERVER_PORT: "9000"
