apiVersion: v1
kind: Service
metadata:
  name: text2pic-service
  namespace: dag-system
spec:
  type: ClusterIP
  selector:
    app: text2pic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000