apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-deployment
  namespace: dag-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      containers:
        - name: llm
          image: docker.io/liuyi585851/labubuai-llm:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
              name: google-secret
            - secretRef:
              name: aws-secret
          env:
            - name: AWS_REGION
              value: "us-east-1"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"