apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-gateway
  namespace: dag-system
  labels:
    app: auth-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-gateway
  template:
    metadata:
      labels:
        app: auth-gateway
    spec:
      containers:
        - name: auth-gateway
          image: docker.io/weimengze/cloud-computing-gateway:v3
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: jwt-secret
          env:
            - name: NO_AUTH_PATHS
              value: "/healthz,/frontend,/backend/user,/"
            - name: PROXY_ROUTES
              value: >
                {
                  "/frontend": "http://frontend.dag-system.svc.cluster.local:80",
                  "/backend/user":     "http://login.dag-system.svc.cluster.local:9000",
                  "/backend/ai-agent": "http://ingress.dag-system.svc.cluster.local:80",
                  "/" : "http://frontend.dag-system.svc.cluster.local:80"
                }  
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10