apiVersion: apps/v1
kind: Deployment
metadata:
  name: pic2text-deployment
  namespace: dag-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pic2text
  template:
    metadata:
      labels:
        app: pic2text
    spec:
      containers:
        - name: pic2text
          image: docker.io/liuyi585851/labubuai-ptt:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: google-secret
            - secretRef:
                name: aws-secret
          env:
            - name: AWS_REGION
              value: "us-east-1"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"