apiVersion: v1
kind: Service
metadata:
  name: pic2text-service
  namespace: dag-system
spec:
  type: ClusterIP
  selector:
    app: pic2text
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000